#!groovy

// Generated by IBM TransformationAdvisor
// Tue Oct 30 12:37:44 UTC 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'daytrader3'
    mvnCommands = '--version'
    test='false'
}